-- Seed data for lemur dictionary app with updated schema (iucn_status + est_protege, named habitations)
BEGIN TRANSACTION;

-- Habitations

-- Amber Mountain National Park | source: http://www.wikidata.org/entity/Q1968934
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (1, -12.59500000, 49.15500000, 'Amber Mountain National Park');

-- Andasibe-Mantadia National Park | source: http://www.wikidata.org/entity/Q2519690
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (2, -18.82666667, 48.44777778, 'Andasibe-Mantadia National Park');

-- Andohahela National Park | source: http://www.wikidata.org/entity/Q1968746
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (3, -24.74130000, 46.73380000, 'Andohahela National Park');

-- Anjanaharibe-Sud Special Reserve | source: http://www.wikidata.org/entity/Q3457632
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (4, -14.70000000, 49.43300000, 'Anjanaharibe-Sud Special Reserve');

-- Ankarafantsika National Park | source: http://www.wikidata.org/entity/Q1936476
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (5, -16.15000000, 46.95000000, 'Ankarafantsika National Park');

-- Ankarana Special Reserve | source: http://www.wikidata.org/entity/Q2306524
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (6, -13.07277778, 48.91472222, 'Ankarana Special Reserve');

-- Baie de Baly National Park | source: http://www.wikidata.org/entity/Q1968753
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (7, -16.08370000, 45.22890000, 'Baie de Baly National Park');

-- Beza Mahafaly Special Reserve | source: http://www.wikidata.org/entity/Q925904
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (8, -23.66666667, 44.60000000, 'Beza Mahafaly Special Reserve');

-- Daraina | source: http://www.wikidata.org/entity/Q3015981
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (9, -13.20000000, 49.66670000, 'Daraina');

-- Isalo National Park | source: http://www.wikidata.org/entity/Q120414
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (10, -22.43510000, 45.28840000, 'Isalo National Park');

-- Kirindy Forest | source: http://www.wikidata.org/entity/Q19462794
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (11, -20.07391389, 44.63071389, 'Kirindy Forest');

-- Lokobe National Park | source: https://en.wikipedia.org/wiki/Lokobe_National_Park
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (12, -13.39917000, 48.31833000, 'Lokobe National Park');

-- Loky-Manambato | source: https://en.wikipedia.org/wiki/Loky-Manambato
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (13, -13.20000000, 49.66700000, 'Loky-Manambato');

-- Makira Protected Area | source: https://en.wikipedia.org/wiki/Makira_Natural_Park
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (14, -15.41300000, 49.53800000, 'Makira Protected Area');

-- Mananara-Nord National Park | source: https://en.wikipedia.org/wiki/Mananara-Nord_National_Park
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (15, -16.16700000, 49.75000000, 'Mananara-Nord National Park');

-- Marojejy National Park | source: http://www.wikidata.org/entity/Q2485097
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (16, -14.43500000, 49.70600000, 'Marojejy National Park');

-- Masoala National Park | source: http://www.wikidata.org/entity/Q964116
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (17, -15.65000000, 50.18333333, 'Masoala National Park');

-- Nosy Mangabe Special Reserve | source: http://www.wikidata.org/entity/Q3936949
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (18, -15.50000000, 49.76666667, 'Nosy Mangabe Special Reserve');

-- Ranomafana National Park | source: http://www.wikidata.org/entity/Q1498242
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (19, -21.21700000, 47.45530000, 'Ranomafana National Park');

-- Tsingy de Bemaraha National Park | source: http://www.wikidata.org/entity/Q1969107
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (20, -18.90061111, 44.81400000, 'Tsingy de Bemaraha National Park');

-- Zombitse-Vohibasia National Park | source: http://www.wikidata.org/entity/Q2762585
INSERT INTO habitation (id, latitude, longitude, nom_habitation) VALUES (21, -22.84140000, 44.68100000, 'Zombitse-Vohibasia National Park');

-- Lemurs
-- Avahi laniger | IUCN (fr): VULNERABLE
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (1, 'Avahi laniger', 'Eastern woolly lemur', 'Petit lemurien indriide nocturne et arboricole a fourrure laineuse brun-gris avec le ventre plus clair. Il passe la journee en boule sur une branche ou dans une fourche d''''arbre et devient actif apres le coucher du soleil, se deplacant par bonds prudents entre quelques arbres favoris. Les couples monogames vivent avec un ou deux jeunes, forment de petits groupes familiaux et emettent des cris doux pour garder le contact. Les adultes mesurent environ 25 a 30 cm de corps pour une queue d''''une longueur similaire et pesent autour de 0,8 a 1,2 kg; aucune forte dominance de sexe n''''est decrite. L''''esperance de vie est estimee a une dizaine d''''annees a l''''etat sauvage, davantage en captivite. Habitat typique: forets et aires protegees autour de Ranomafana National Park.', 'Folivore strict: jeunes feuilles, bourgeons et fleurs consommes la nuit; fruits rarement pris.', 'VULNERABLE', 1);

-- Avahi occidentalis | IUCN (fr): VULNERABLE
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (2, 'Avahi occidentalis', 'Western woolly lemur', 'Petit lemurien indriide nocturne et arboricole a fourrure laineuse brun-gris avec le ventre plus clair. Il passe la journee en boule sur une branche ou dans une fourche d''''arbre et devient actif apres le coucher du soleil, se deplacant par bonds prudents entre quelques arbres favoris. Les couples monogames vivent avec un ou deux jeunes, forment de petits groupes familiaux et emettent des cris doux pour garder le contact. Les adultes mesurent environ 25 a 30 cm de corps pour une queue d''''une longueur similaire et pesent autour de 0,8 a 1,2 kg; aucune forte dominance de sexe n''''est decrite. L''''esperance de vie est estimee a une dizaine d''''annees a l''''etat sauvage, davantage en captivite. Habitat typique: forets et aires protegees autour de Ankarafantsika National Park.', 'Folivore strict: jeunes feuilles, bourgeons et fleurs consommes la nuit; fruits rarement pris.', 'VULNERABLE', 1);

-- Avahi peyrierasi | IUCN (fr): VULNERABLE
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (3, 'Avahi peyrierasi', 'Peyrieras'' woolly lemur', 'Petit lemurien indriide nocturne et arboricole a fourrure laineuse brun-gris avec le ventre plus clair. Il passe la journee en boule sur une branche ou dans une fourche d''''arbre et devient actif apres le coucher du soleil, se deplacant par bonds prudents entre quelques arbres favoris. Les couples monogames vivent avec un ou deux jeunes, forment de petits groupes familiaux et emettent des cris doux pour garder le contact. Les adultes mesurent environ 25 a 30 cm de corps pour une queue d''''une longueur similaire et pesent autour de 0,8 a 1,2 kg; aucune forte dominance de sexe n''''est decrite. L''''esperance de vie est estimee a une dizaine d''''annees a l''''etat sauvage, davantage en captivite. Habitat typique: forets et aires protegees autour de Andohahela National Park.', 'Folivore strict: jeunes feuilles, bourgeons et fleurs consommes la nuit; fruits rarement pris.', 'VULNERABLE', 1);

-- Eulemur albifrons | IUCN (fr): VULNERABLE
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (4, 'Eulemur albifrons', 'Eulemur albifrons', 'Lemurien marron de taille moyenne au pelage generalement brun-gris avec un masque facial contraste et un ventre plus clair, le dimorphisme sexuel de coloration etant frequent. C''''est une espece cathemérale: les groupes sont actifs par episodes de jour comme de nuit, avec des pics d''''activite au lever et au coucher du soleil pour exploiter les fruits murs. Il vit en groupes mixtes de 5 a plus de 12 individus, comportant plusieurs males et femelles adultes; comme chez de nombreux lemuriens, les femelles occupent souvent la position dominante et decident des deplacements. Les adultes mesurent en moyenne 35 a 40 cm de corps pour une queue touffue de 40 a 50 cm et pesent environ 2 a 2,5 kg. En captivite, des individus depassent couramment 20 ans, l''''esperance de vie etant plus faible en nature. Habitat typique: forets et aires protegees autour de Masoala National Park.', 'Frugivore generaliste: fruits en majorite, plus feuilles, fleurs et graines; regime catheméral (activite de jour et de nuit).', 'VULNERABLE', 1);

-- Eulemur collaris | IUCN (fr): EN VOIE DE DISPARITION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (5, 'Eulemur collaris', 'Eulemur collaris', 'Lemurien marron de taille moyenne au pelage generalement brun-gris avec un masque facial contraste et un ventre plus clair, le dimorphisme sexuel de coloration etant frequent. C''''est une espece cathemérale: les groupes sont actifs par episodes de jour comme de nuit, avec des pics d''''activite au lever et au coucher du soleil pour exploiter les fruits murs. Il vit en groupes mixtes de 5 a plus de 12 individus, comportant plusieurs males et femelles adultes; comme chez de nombreux lemuriens, les femelles occupent souvent la position dominante et decident des deplacements. Les adultes mesurent en moyenne 35 a 40 cm de corps pour une queue touffue de 40 a 50 cm et pesent environ 2 a 2,5 kg. En captivite, des individus depassent couramment 20 ans, l''''esperance de vie etant plus faible en nature. Habitat typique: forets et aires protegees autour de Andohahela National Park.', 'Frugivore generaliste: fruits en majorite, plus feuilles, fleurs et graines; regime catheméral (activite de jour et de nuit).', 'EN VOIE DE DISPARITION', 1);

-- Eulemur collaris rufifrons | IUCN (fr): VULNERABLE
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (6, 'Eulemur collaris rufifrons', 'Eulemur collaris rufifrons', 'Lemurien marron de taille moyenne au pelage generalement brun-gris avec un masque facial contraste et un ventre plus clair, le dimorphisme sexuel de coloration etant frequent. C''''est une espece cathemérale: les groupes sont actifs par episodes de jour comme de nuit, avec des pics d''''activite au lever et au coucher du soleil pour exploiter les fruits murs. Il vit en groupes mixtes de 5 a plus de 12 individus, comportant plusieurs males et femelles adultes; comme chez de nombreux lemuriens, les femelles occupent souvent la position dominante et decident des deplacements. Les adultes mesurent en moyenne 35 a 40 cm de corps pour une queue touffue de 40 a 50 cm et pesent environ 2 a 2,5 kg. En captivite, des individus depassent couramment 20 ans, l''''esperance de vie etant plus faible en nature. Habitat typique: forets et aires protegees autour de Andohahela National Park.', 'Frugivore generaliste: fruits en majorite, plus feuilles, fleurs et graines; regime catheméral (activite de jour et de nuit).', 'VULNERABLE', 1);

-- Eulemur coronatus | IUCN (fr): EN VOIE DE DISPARITION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (7, 'Eulemur coronatus', 'Lémur couronné', 'Lemurien marron de taille moyenne au pelage generalement brun-gris avec un masque facial contraste et un ventre plus clair, le dimorphisme sexuel de coloration etant frequent. C''''est une espece cathemérale: les groupes sont actifs par episodes de jour comme de nuit, avec des pics d''''activite au lever et au coucher du soleil pour exploiter les fruits murs. Il vit en groupes mixtes de 5 a plus de 12 individus, comportant plusieurs males et femelles adultes; comme chez de nombreux lemuriens, les femelles occupent souvent la position dominante et decident des deplacements. Les adultes mesurent en moyenne 35 a 40 cm de corps pour une queue touffue de 40 a 50 cm et pesent environ 2 a 2,5 kg. En captivite, des individus depassent couramment 20 ans, l''''esperance de vie etant plus faible en nature. Habitat typique: forets et aires protegees autour de Amber Mountain National Park.', 'Frugivore generaliste: fruits en majorite, plus feuilles, fleurs et graines; regime catheméral (activite de jour et de nuit).', 'EN VOIE DE DISPARITION', 1);

-- Eulemur fulvus | IUCN (fr): VULNERABLE
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (8, 'Eulemur fulvus', 'Lémur fauve', 'Lemurien marron de taille moyenne au pelage generalement brun-gris avec un masque facial contraste et un ventre plus clair, le dimorphisme sexuel de coloration etant frequent. C''''est une espece cathemérale: les groupes sont actifs par episodes de jour comme de nuit, avec des pics d''''activite au lever et au coucher du soleil pour exploiter les fruits murs. Il vit en groupes mixtes de 5 a plus de 12 individus, comportant plusieurs males et femelles adultes; comme chez de nombreux lemuriens, les femelles occupent souvent la position dominante et decident des deplacements. Les adultes mesurent en moyenne 35 a 40 cm de corps pour une queue touffue de 40 a 50 cm et pesent environ 2 a 2,5 kg. En captivite, des individus depassent couramment 20 ans, l''''esperance de vie etant plus faible en nature. Habitat typique: forets et aires protegees autour de Ankarafantsika National Park.', 'Frugivore generaliste: fruits en majorite, plus feuilles, fleurs et graines; regime catheméral (activite de jour et de nuit).', 'VULNERABLE', 1);

-- Eulemur macaco | IUCN (fr): EN VOIE DE DISPARITION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (9, 'Eulemur macaco', 'Lémur noir', 'Lemurien marron de taille moyenne au pelage generalement brun-gris avec un masque facial contraste et un ventre plus clair, le dimorphisme sexuel de coloration etant frequent. C''''est une espece cathemérale: les groupes sont actifs par episodes de jour comme de nuit, avec des pics d''''activite au lever et au coucher du soleil pour exploiter les fruits murs. Il vit en groupes mixtes de 5 a plus de 12 individus, comportant plusieurs males et femelles adultes; comme chez de nombreux lemuriens, les femelles occupent souvent la position dominante et decident des deplacements. Les adultes mesurent en moyenne 35 a 40 cm de corps pour une queue touffue de 40 a 50 cm et pesent environ 2 a 2,5 kg. En captivite, des individus depassent couramment 20 ans, l''''esperance de vie etant plus faible en nature. Habitat typique: forets et aires protegees autour de Lokobe National Park.', 'Frugivore generaliste: fruits en majorite, plus feuilles, fleurs et graines; regime catheméral (activite de jour et de nuit).', 'EN VOIE DE DISPARITION', 1);

-- Eulemur mongoz | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (10, 'Eulemur mongoz', 'Lémur mongos', 'Lemurien marron de taille moyenne au pelage generalement brun-gris avec un masque facial contraste et un ventre plus clair, le dimorphisme sexuel de coloration etant frequent. C''''est une espece cathemérale: les groupes sont actifs par episodes de jour comme de nuit, avec des pics d''''activite au lever et au coucher du soleil pour exploiter les fruits murs. Il vit en groupes mixtes de 5 a plus de 12 individus, comportant plusieurs males et femelles adultes; comme chez de nombreux lemuriens, les femelles occupent souvent la position dominante et decident des deplacements. Les adultes mesurent en moyenne 35 a 40 cm de corps pour une queue touffue de 40 a 50 cm et pesent environ 2 a 2,5 kg. En captivite, des individus depassent couramment 20 ans, l''''esperance de vie etant plus faible en nature. Habitat typique: forets et aires protegees autour de Ankarafantsika National Park.', 'Frugivore generaliste: fruits en majorite, plus feuilles, fleurs et graines; regime catheméral (activite de jour et de nuit).', 'EN DANGER CRITIQUE EXTINCTION', 1);

-- Eulemur rubriventer | IUCN (fr): VULNERABLE
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (11, 'Eulemur rubriventer', 'Lémur à ventre roux', 'Lemurien marron de taille moyenne au pelage generalement brun-gris avec un masque facial contraste et un ventre plus clair, le dimorphisme sexuel de coloration etant frequent. C''''est une espece cathemérale: les groupes sont actifs par episodes de jour comme de nuit, avec des pics d''''activite au lever et au coucher du soleil pour exploiter les fruits murs. Il vit en groupes mixtes de 5 a plus de 12 individus, comportant plusieurs males et femelles adultes; comme chez de nombreux lemuriens, les femelles occupent souvent la position dominante et decident des deplacements. Les adultes mesurent en moyenne 35 a 40 cm de corps pour une queue touffue de 40 a 50 cm et pesent environ 2 a 2,5 kg. En captivite, des individus depassent couramment 20 ans, l''''esperance de vie etant plus faible en nature. Habitat typique: forets et aires protegees autour de Ranomafana National Park.', 'Frugivore generaliste: fruits en majorite, plus feuilles, fleurs et graines; regime catheméral (activite de jour et de nuit).', 'VULNERABLE', 1);

-- Eulemur rufifrons | IUCN (fr): VULNERABLE
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (12, 'Eulemur rufifrons', 'Eulemur rufifrons', 'Lemurien marron de taille moyenne au pelage generalement brun-gris avec un masque facial contraste et un ventre plus clair, le dimorphisme sexuel de coloration etant frequent. C''''est une espece cathemérale: les groupes sont actifs par episodes de jour comme de nuit, avec des pics d''''activite au lever et au coucher du soleil pour exploiter les fruits murs. Il vit en groupes mixtes de 5 a plus de 12 individus, comportant plusieurs males et femelles adultes; comme chez de nombreux lemuriens, les femelles occupent souvent la position dominante et decident des deplacements. Les adultes mesurent en moyenne 35 a 40 cm de corps pour une queue touffue de 40 a 50 cm et pesent environ 2 a 2,5 kg. En captivite, des individus depassent couramment 20 ans, l''''esperance de vie etant plus faible en nature. Habitat typique: forets et aires protegees autour de Kirindy Forest.', 'Frugivore generaliste: fruits en majorite, plus feuilles, fleurs et graines; regime catheméral (activite de jour et de nuit).', 'VULNERABLE', 1);

-- Eulemur rufus | IUCN (fr): VULNERABLE
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (13, 'Eulemur rufus', 'Eulemur rufus', 'Lemurien marron de taille moyenne au pelage generalement brun-gris avec un masque facial contraste et un ventre plus clair, le dimorphisme sexuel de coloration etant frequent. C''''est une espece cathemérale: les groupes sont actifs par episodes de jour comme de nuit, avec des pics d''''activite au lever et au coucher du soleil pour exploiter les fruits murs. Il vit en groupes mixtes de 5 a plus de 12 individus, comportant plusieurs males et femelles adultes; comme chez de nombreux lemuriens, les femelles occupent souvent la position dominante et decident des deplacements. Les adultes mesurent en moyenne 35 a 40 cm de corps pour une queue touffue de 40 a 50 cm et pesent environ 2 a 2,5 kg. En captivite, des individus depassent couramment 20 ans, l''''esperance de vie etant plus faible en nature. Habitat typique: forets et aires protegees autour de Ankarafantsika National Park.', 'Frugivore generaliste: fruits en majorite, plus feuilles, fleurs et graines; regime catheméral (activite de jour et de nuit).', 'VULNERABLE', 1);

-- Eulemur sanfordi | IUCN (fr): EN VOIE DE DISPARITION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (14, 'Eulemur sanfordi', 'Eulemur sanfordi', 'Lemurien marron de taille moyenne au pelage generalement brun-gris avec un masque facial contraste et un ventre plus clair, le dimorphisme sexuel de coloration etant frequent. C''''est une espece cathemérale: les groupes sont actifs par episodes de jour comme de nuit, avec des pics d''''activite au lever et au coucher du soleil pour exploiter les fruits murs. Il vit en groupes mixtes de 5 a plus de 12 individus, comportant plusieurs males et femelles adultes; comme chez de nombreux lemuriens, les femelles occupent souvent la position dominante et decident des deplacements. Les adultes mesurent en moyenne 35 a 40 cm de corps pour une queue touffue de 40 a 50 cm et pesent environ 2 a 2,5 kg. En captivite, des individus depassent couramment 20 ans, l''''esperance de vie etant plus faible en nature. Habitat typique: forets et aires protegees autour de Amber Mountain National Park.', 'Frugivore generaliste: fruits en majorite, plus feuilles, fleurs et graines; regime catheméral (activite de jour et de nuit).', 'EN VOIE DE DISPARITION', 1);

-- Hapalemur aureus | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (15, 'Hapalemur aureus', 'Hapalémur doré', 'Petit lemurien bambou au pelage gris-olive ou dore avec ventre plus clair, specialise dans l''''exploitation des bambouseraies. Il est surtout crepusculaire et nocturne, concentrant son activite autour de l''''aube et du crepuscule pour se nourrir de jeunes pousses de bambou riches en fibres et parfois en composés cyanogenes. Les groupes comptent generalement de 2 a 11 individus, souvent centres sur une femelle adulte et ses petits. Les adultes mesurent autour de 25 a 35 cm de corps pour une queue de longueur comparable et pesent environ 1 a 2,5 kg selon l''''espece. Ils peuvent vivre autour de 15 ans en captivite lorsque l''''habitat et la nourriture sont assures. Habitat typique: forets et aires protegees autour de Ranomafana National Park.', 'Specialiste du bambou: jeunes pousses, feuilles et tiges, capable de tolerer le cyanure contenu dans certaines especes; complete avec quelques fruits et herbes.', 'EN DANGER CRITIQUE EXTINCTION', 1);

-- Hapalemur griseus | IUCN (fr): VULNERABLE
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (16, 'Hapalemur griseus', 'Hapalémur gris', 'Petit lemurien bambou au pelage gris-olive ou dore avec ventre plus clair, specialise dans l''''exploitation des bambouseraies. Il est surtout crepusculaire et nocturne, concentrant son activite autour de l''''aube et du crepuscule pour se nourrir de jeunes pousses de bambou riches en fibres et parfois en composés cyanogenes. Les groupes comptent generalement de 2 a 11 individus, souvent centres sur une femelle adulte et ses petits. Les adultes mesurent autour de 25 a 35 cm de corps pour une queue de longueur comparable et pesent environ 1 a 2,5 kg selon l''''espece. Ils peuvent vivre autour de 15 ans en captivite lorsque l''''habitat et la nourriture sont assures. Habitat typique: forets et aires protegees autour de Ranomafana National Park.', 'Specialiste du bambou: jeunes pousses, feuilles et tiges, capable de tolerer le cyanure contenu dans certaines especes; complete avec quelques fruits et herbes.', 'VULNERABLE', 1);

-- Hapalemur occidentalis | IUCN (fr): VULNERABLE
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (17, 'Hapalemur occidentalis', 'Hapalemur occidentalis', 'Petit lemurien bambou au pelage gris-olive ou dore avec ventre plus clair, specialise dans l''''exploitation des bambouseraies. Il est surtout crepusculaire et nocturne, concentrant son activite autour de l''''aube et du crepuscule pour se nourrir de jeunes pousses de bambou riches en fibres et parfois en composés cyanogenes. Les groupes comptent generalement de 2 a 11 individus, souvent centres sur une femelle adulte et ses petits. Les adultes mesurent autour de 25 a 35 cm de corps pour une queue de longueur comparable et pesent environ 1 a 2,5 kg selon l''''espece. Ils peuvent vivre autour de 15 ans en captivite lorsque l''''habitat et la nourriture sont assures. Habitat typique: forets et aires protegees autour de Ankarafantsika National Park.', 'Specialiste du bambou: jeunes pousses, feuilles et tiges, capable de tolerer le cyanure contenu dans certaines especes; complete avec quelques fruits et herbes.', 'VULNERABLE', 1);

-- Indri indri | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (18, 'Indri indri', 'Indri indri', 'Plus grand lemurien vivant, indriide robuste au pelage noir et blanc tres contraste et a la queue rudimentaire. Strictement diurne, il commence la journee par de puissants chants territoriaux audibles sur plusieurs kilometres, puis passe l''''essentiel de son temps a se deplacer et a s''''alimenter dans la canopee. Il vit en petits groupes familiaux de 2 a 6 individus, souvent un couple monogame et ses jeunes, avec une cohesion forte et des comportements d''''allogrooming. Les adultes mesurent environ 60 a 75 cm de corps pour 6 a 9,5 kg; les femelles peuvent etre legerement plus lourdes que les males. En environnement protege, ils peuvent depasser 20 ans, mais la perte d''''habitat reduit probablement cette esperance de vie a l''''etat sauvage. Habitat typique: forets et aires protegees autour de Andasibe-Mantadia National Park.', 'Régime folivore-frugivore domine par les feuilles et jeunes pousses, plus fruits, fleurs et ecorce selon la saison.', 'EN DANGER CRITIQUE EXTINCTION', 1);

-- Lemur catta | IUCN (fr): EN VOIE DE DISPARITION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (19, 'Lemur catta', 'lémur catta', 'Lemurien emblématique a longue queue annelée noire et blanche, au dos gris et au ventre clair, tres reconnaissable. Strictement diurne et souvent terrestre, il passe beaucoup de temps au sol dans les forets seches et les paysages rocheux, pratique des bains de soleil matinaux en posture assise. Il vit en grands groupes mixtes de 6 a plus de 20 individus, avec un systeme social fortement matriarcal ou les femelles dominent les males pour l''''acces aux ressources et aux partenaires. Les adultes pesent environ 2,2 a 3,1 kg, avec un corps de 39 a 46 cm et une queue de 56 a 63 cm. L''''esperance de vie est de l''''ordre de 15 a 20 ans en nature, pouvant atteindre pres de 30 ans en captivite. Habitat typique: forets et aires protegees autour de Isalo National Park.', 'Omnivore opportuniste: fruits, feuilles, fleurs, jeunes pousses, seve et parfois insectes ou autres petits invertébrés.', 'EN VOIE DE DISPARITION', 1);

-- Lepilemur ankaranensis | IUCN (fr): EN VOIE DE DISPARITION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (20, 'Lepilemur ankaranensis', 'Lepilemur ankaranensis', 'Petit lemurien sportif nocturne a grands yeux, pelage brun-gris et longue queue touffue, specialise dans les forets seches et galeries ripicoles. Strictement nocturne, il passe la journee dans des cavites d''''arbres ou des trous de rocher et sort la nuit pour se nourrir de feuilles, se deplacant par bonds entre quelques arbres favoris. L''''espece est essentiellement solitaire: chaque adulte defend un petit domaine vital, les contacts sociaux etant limites a la reproduction et aux soins aux jeunes. Les adultes mesurent environ 25 a 30 cm de corps pour une queue de longueur similaire et pesent de 0,7 a 1 kg. Les donnees suggerent une esperance de vie de l''''ordre de 8 a 12 ans a l''''etat sauvage. Habitat typique: forets et aires protegees autour de Ankarana Special Reserve.', 'Folivore nocturne: feuilles matures et jeunes feuilles, plus fleurs et ecorce; digestion lente avec longues phases de repos.', 'EN VOIE DE DISPARITION', 1);

-- Lepilemur edwardsi | IUCN (fr): EN VOIE DE DISPARITION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (21, 'Lepilemur edwardsi', 'Lepilemur edwardsi', 'Petit lemurien sportif nocturne a grands yeux, pelage brun-gris et longue queue touffue, specialise dans les forets seches et galeries ripicoles. Strictement nocturne, il passe la journee dans des cavites d''''arbres ou des trous de rocher et sort la nuit pour se nourrir de feuilles, se deplacant par bonds entre quelques arbres favoris. L''''espece est essentiellement solitaire: chaque adulte defend un petit domaine vital, les contacts sociaux etant limites a la reproduction et aux soins aux jeunes. Les adultes mesurent environ 25 a 30 cm de corps pour une queue de longueur similaire et pesent de 0,7 a 1 kg. Les donnees suggerent une esperance de vie de l''''ordre de 8 a 12 ans a l''''etat sauvage. Habitat typique: forets et aires protegees autour de Kirindy Forest.', 'Folivore nocturne: feuilles matures et jeunes feuilles, plus fleurs et ecorce; digestion lente avec longues phases de repos.', 'EN VOIE DE DISPARITION', 1);

-- Lepilemur hubbardorum | IUCN (fr): EN VOIE DE DISPARITION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (22, 'Lepilemur hubbardorum', 'Lepilemur hubbardorum', 'Petit lemurien sportif nocturne a grands yeux, pelage brun-gris et longue queue touffue, specialise dans les forets seches et galeries ripicoles. Strictement nocturne, il passe la journee dans des cavites d''''arbres ou des trous de rocher et sort la nuit pour se nourrir de feuilles, se deplacant par bonds entre quelques arbres favoris. L''''espece est essentiellement solitaire: chaque adulte defend un petit domaine vital, les contacts sociaux etant limites a la reproduction et aux soins aux jeunes. Les adultes mesurent environ 25 a 30 cm de corps pour une queue de longueur similaire et pesent de 0,7 a 1 kg. Les donnees suggerent une esperance de vie de l''''ordre de 8 a 12 ans a l''''etat sauvage. Habitat typique: forets et aires protegees autour de Zombitse-Vohibasia National Park.', 'Folivore nocturne: feuilles matures et jeunes feuilles, plus fleurs et ecorce; digestion lente avec longues phases de repos.', 'EN VOIE DE DISPARITION', 1);

-- Lepilemur leucopus | IUCN (fr): EN VOIE DE DISPARITION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (23, 'Lepilemur leucopus', 'Lépilémur à pattes blanches', 'Petit lemurien sportif nocturne a grands yeux, pelage brun-gris et longue queue touffue, specialise dans les forets seches et galeries ripicoles. Strictement nocturne, il passe la journee dans des cavites d''''arbres ou des trous de rocher et sort la nuit pour se nourrir de feuilles, se deplacant par bonds entre quelques arbres favoris. L''''espece est essentiellement solitaire: chaque adulte defend un petit domaine vital, les contacts sociaux etant limites a la reproduction et aux soins aux jeunes. Les adultes mesurent environ 25 a 30 cm de corps pour une queue de longueur similaire et pesent de 0,7 a 1 kg. Les donnees suggerent une esperance de vie de l''''ordre de 8 a 12 ans a l''''etat sauvage. Habitat typique: forets et aires protegees autour de Beza Mahafaly Special Reserve.', 'Folivore nocturne: feuilles matures et jeunes feuilles, plus fleurs et ecorce; digestion lente avec longues phases de repos.', 'EN VOIE DE DISPARITION', 1);

-- Lepilemur ruficaudatus | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (24, 'Lepilemur ruficaudatus', 'Lepilemur ruficaudatus', 'Petit lemurien sportif nocturne a grands yeux, pelage brun-gris et longue queue touffue, specialise dans les forets seches et galeries ripicoles. Strictement nocturne, il passe la journee dans des cavites d''''arbres ou des trous de rocher et sort la nuit pour se nourrir de feuilles, se deplacant par bonds entre quelques arbres favoris. L''''espece est essentiellement solitaire: chaque adulte defend un petit domaine vital, les contacts sociaux etant limites a la reproduction et aux soins aux jeunes. Les adultes mesurent environ 25 a 30 cm de corps pour une queue de longueur similaire et pesent de 0,7 a 1 kg. Les donnees suggerent une esperance de vie de l''''ordre de 8 a 12 ans a l''''etat sauvage. Habitat typique: forets et aires protegees autour de Kirindy Forest.', 'Folivore nocturne: feuilles matures et jeunes feuilles, plus fleurs et ecorce; digestion lente avec longues phases de repos.', 'EN DANGER CRITIQUE EXTINCTION', 1);

-- Lepilemur tymerlachsoni | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (25, 'Lepilemur tymerlachsoni', 'Lepilemur tymerlachsoni', 'Petit lemurien sportif nocturne a grands yeux, pelage brun-gris et longue queue touffue, specialise dans les forets seches et galeries ripicoles. Strictement nocturne, il passe la journee dans des cavites d''''arbres ou des trous de rocher et sort la nuit pour se nourrir de feuilles, se deplacant par bonds entre quelques arbres favoris. L''''espece est essentiellement solitaire: chaque adulte defend un petit domaine vital, les contacts sociaux etant limites a la reproduction et aux soins aux jeunes. Les adultes mesurent environ 25 a 30 cm de corps pour une queue de longueur similaire et pesent de 0,7 a 1 kg. Les donnees suggerent une esperance de vie de l''''ordre de 8 a 12 ans a l''''etat sauvage. Habitat typique: forets et aires protegees autour de Lokobe National Park.', 'Folivore nocturne: feuilles matures et jeunes feuilles, plus fleurs et ecorce; digestion lente avec longues phases de repos.', 'EN DANGER CRITIQUE EXTINCTION', 1);

-- Prolemur simus | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (26, 'Prolemur simus', 'Grand Hapalémur', 'Petit lemurien bambou au pelage gris-olive ou dore avec ventre plus clair, specialise dans l''''exploitation des bambouseraies. Il est surtout crepusculaire et nocturne, concentrant son activite autour de l''''aube et du crepuscule pour se nourrir de jeunes pousses de bambou riches en fibres et parfois en composés cyanogenes. Les groupes comptent generalement de 2 a 11 individus, souvent centres sur une femelle adulte et ses petits. Les adultes mesurent autour de 25 a 35 cm de corps pour une queue de longueur comparable et pesent environ 1 a 2,5 kg selon l''''espece. Ils peuvent vivre autour de 15 ans en captivite lorsque l''''habitat et la nourriture sont assures. Habitat typique: forets et aires protegees autour de Ranomafana National Park.', 'Specialiste du bambou: jeunes pousses, feuilles et tiges, capable de tolerer le cyanure contenu dans certaines especes; complete avec quelques fruits et herbes.', 'EN DANGER CRITIQUE EXTINCTION', 1);

-- Propithecus candidus | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (27, 'Propithecus candidus', 'Silky sifaka', 'Sifaka de taille moyenne ou grande au pelage dense generalement clair (blanc, creme ou brun) avec des zones plus sombres selon l''''espece, se deplacant en position verticale par grands bonds entre les troncs. Strictement diurne et arboricole, il passe la majeure partie de la journee a se deplacer dans la canopee a la recherche de feuilles, jeunes pousses et fruits, et effectue parfois ses fameux sauts en danse au sol. Les groupes sociaux comptent en general 3 a 10 individus avec plusieurs adultes; la dominance des femelles sur les males est bien documentee dans plusieurs especes de sifakas. Les adultes mesurent environ 45 a 55 cm de corps pour une queue de longueur comparable et pesent de 3 a 6,5 kg selon l''''espece. Des etudes de long terme montrent que certains individus peuvent depasser 20 a 25 ans, voire 30 ans, surtout dans des conditions protegees. Habitat typique: forets et aires protegees autour de Marojejy National Park.', 'Principalement folivore (feuilles, jeunes pousses) avec une part importante de fruits et de fleurs; consomme aussi graines et ecorce.', 'EN DANGER CRITIQUE EXTINCTION', 1);

-- Propithecus coquereli | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (28, 'Propithecus coquereli', 'Coquerel''s sifaka', 'Sifaka de taille moyenne ou grande au pelage dense generalement clair (blanc, creme ou brun) avec des zones plus sombres selon l''''espece, se deplacant en position verticale par grands bonds entre les troncs. Strictement diurne et arboricole, il passe la majeure partie de la journee a se deplacer dans la canopee a la recherche de feuilles, jeunes pousses et fruits, et effectue parfois ses fameux sauts en danse au sol. Les groupes sociaux comptent en general 3 a 10 individus avec plusieurs adultes; la dominance des femelles sur les males est bien documentee dans plusieurs especes de sifakas. Les adultes mesurent environ 45 a 55 cm de corps pour une queue de longueur comparable et pesent de 3 a 6,5 kg selon l''''espece. Des etudes de long terme montrent que certains individus peuvent depasser 20 a 25 ans, voire 30 ans, surtout dans des conditions protegees. Habitat typique: forets et aires protegees autour de Ankarafantsika National Park.', 'Principalement folivore (feuilles, jeunes pousses) avec une part importante de fruits et de fleurs; consomme aussi graines et ecorce.', 'EN DANGER CRITIQUE EXTINCTION', 1);

-- Propithecus deckenii | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (29, 'Propithecus deckenii', 'Von der Decken''s sifaka', 'Sifaka de taille moyenne ou grande au pelage dense generalement clair (blanc, creme ou brun) avec des zones plus sombres selon l''''espece, se deplacant en position verticale par grands bonds entre les troncs. Strictement diurne et arboricole, il passe la majeure partie de la journee a se deplacer dans la canopee a la recherche de feuilles, jeunes pousses et fruits, et effectue parfois ses fameux sauts en danse au sol. Les groupes sociaux comptent en general 3 a 10 individus avec plusieurs adultes; la dominance des femelles sur les males est bien documentee dans plusieurs especes de sifakas. Les adultes mesurent environ 45 a 55 cm de corps pour une queue de longueur comparable et pesent de 3 a 6,5 kg selon l''''espece. Des etudes de long terme montrent que certains individus peuvent depasser 20 a 25 ans, voire 30 ans, surtout dans des conditions protegees. Habitat typique: forets et aires protegees autour de Tsingy de Bemaraha National Park.', 'Principalement folivore (feuilles, jeunes pousses) avec une part importante de fruits et de fleurs; consomme aussi graines et ecorce.', 'EN DANGER CRITIQUE EXTINCTION', 1);

-- Propithecus diadema | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (30, 'Propithecus diadema', 'Diademed sifaka', 'Sifaka de taille moyenne ou grande au pelage dense generalement clair (blanc, creme ou brun) avec des zones plus sombres selon l''''espece, se deplacant en position verticale par grands bonds entre les troncs. Strictement diurne et arboricole, il passe la majeure partie de la journee a se deplacer dans la canopee a la recherche de feuilles, jeunes pousses et fruits, et effectue parfois ses fameux sauts en danse au sol. Les groupes sociaux comptent en general 3 a 10 individus avec plusieurs adultes; la dominance des femelles sur les males est bien documentee dans plusieurs especes de sifakas. Les adultes mesurent environ 45 a 55 cm de corps pour une queue de longueur comparable et pesent de 3 a 6,5 kg selon l''''espece. Des etudes de long terme montrent que certains individus peuvent depasser 20 a 25 ans, voire 30 ans, surtout dans des conditions protegees. Habitat typique: forets et aires protegees autour de Andasibe-Mantadia National Park.', 'Principalement folivore (feuilles, jeunes pousses) avec une part importante de fruits et de fleurs; consomme aussi graines et ecorce.', 'EN DANGER CRITIQUE EXTINCTION', 1);

-- Propithecus edwardsi | IUCN (fr): EN VOIE DE DISPARITION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (31, 'Propithecus edwardsi', 'Milne-Edwards'' sifaka', 'Sifaka de taille moyenne ou grande au pelage dense generalement clair (blanc, creme ou brun) avec des zones plus sombres selon l''''espece, se deplacant en position verticale par grands bonds entre les troncs. Strictement diurne et arboricole, il passe la majeure partie de la journee a se deplacer dans la canopee a la recherche de feuilles, jeunes pousses et fruits, et effectue parfois ses fameux sauts en danse au sol. Les groupes sociaux comptent en general 3 a 10 individus avec plusieurs adultes; la dominance des femelles sur les males est bien documentee dans plusieurs especes de sifakas. Les adultes mesurent environ 45 a 55 cm de corps pour une queue de longueur comparable et pesent de 3 a 6,5 kg selon l''''espece. Des etudes de long terme montrent que certains individus peuvent depasser 20 a 25 ans, voire 30 ans, surtout dans des conditions protegees. Habitat typique: forets et aires protegees autour de Ranomafana National Park.', 'Principalement folivore (feuilles, jeunes pousses) avec une part importante de fruits et de fleurs; consomme aussi graines et ecorce.', 'EN VOIE DE DISPARITION', 1);

-- Propithecus tattersalli | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (32, 'Propithecus tattersalli', 'Golden-crowned sifaka', 'Sifaka de taille moyenne ou grande au pelage dense generalement clair (blanc, creme ou brun) avec des zones plus sombres selon l''''espece, se deplacant en position verticale par grands bonds entre les troncs. Strictement diurne et arboricole, il passe la majeure partie de la journee a se deplacer dans la canopee a la recherche de feuilles, jeunes pousses et fruits, et effectue parfois ses fameux sauts en danse au sol. Les groupes sociaux comptent en general 3 a 10 individus avec plusieurs adultes; la dominance des femelles sur les males est bien documentee dans plusieurs especes de sifakas. Les adultes mesurent environ 45 a 55 cm de corps pour une queue de longueur comparable et pesent de 3 a 6,5 kg selon l''''espece. Des etudes de long terme montrent que certains individus peuvent depasser 20 a 25 ans, voire 30 ans, surtout dans des conditions protegees. Habitat typique: forets et aires protegees autour de Loky-Manambato.', 'Principalement folivore (feuilles, jeunes pousses) avec une part importante de fruits et de fleurs; consomme aussi graines et ecorce.', 'EN DANGER CRITIQUE EXTINCTION', 1);

-- Propithecus verreauxi | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (33, 'Propithecus verreauxi', 'Verreaux''s sifaka', 'Sifaka de taille moyenne ou grande au pelage dense generalement clair (blanc, creme ou brun) avec des zones plus sombres selon l''''espece, se deplacant en position verticale par grands bonds entre les troncs. Strictement diurne et arboricole, il passe la majeure partie de la journee a se deplacer dans la canopee a la recherche de feuilles, jeunes pousses et fruits, et effectue parfois ses fameux sauts en danse au sol. Les groupes sociaux comptent en general 3 a 10 individus avec plusieurs adultes; la dominance des femelles sur les males est bien documentee dans plusieurs especes de sifakas. Les adultes mesurent environ 45 a 55 cm de corps pour une queue de longueur comparable et pesent de 3 a 6,5 kg selon l''''espece. Des etudes de long terme montrent que certains individus peuvent depasser 20 a 25 ans, voire 30 ans, surtout dans des conditions protegees. Habitat typique: forets et aires protegees autour de Beza Mahafaly Special Reserve.', 'Principalement folivore (feuilles, jeunes pousses) avec une part importante de fruits et de fleurs; consomme aussi graines et ecorce.', 'EN DANGER CRITIQUE EXTINCTION', 1);

-- Varecia rubra | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (34, 'Varecia rubra', 'Vari roux', 'Grand lemurien ruffed (varika) au pelage epais et bicolore, rouge et noir ou noir et blanc selon l''''espece, avec une large collerette de fourrure autour de la tete. Principalement diurne mais pouvant presenter une activite crepusculaire marquee, il se deplace dans les hautes branches a la recherche de gros fruits juteux. Il vit en communautes fission-fusion ou plusieurs femelles parentes partagent un territoire riche en arbres fruitiers, utilisant des nids foliacés pour elever les petits. Les adultes mesurent environ 50 a 60 cm de corps pour une queue touffue de 50 a 65 cm et pesent de 3 a 4,5 kg. Des donnees de captivite indiquent une esperance de vie pouvant atteindre ou depasser 30 ans, probablement plus faible en nature. Habitat typique: forets et aires protegees autour de Masoala National Park.', 'Fortement frugivore (gros fruits juteux), mais consomme aussi nectar, fleurs et feuilles; role cle dans la dispersion des grosses graines.', 'EN DANGER CRITIQUE EXTINCTION', 1);

-- Varecia variegata | IUCN (fr): EN DANGER CRITIQUE EXTINCTION
INSERT INTO lemur (id, nom_scientifique, nom_commun, description, alimentation, iucn_status, est_protege) VALUES (35, 'Varecia variegata', 'black-and-white ruffed lemur', 'Grand lemurien ruffed (varika) au pelage epais et bicolore, rouge et noir ou noir et blanc selon l''''espece, avec une large collerette de fourrure autour de la tete. Principalement diurne mais pouvant presenter une activite crepusculaire marquee, il se deplace dans les hautes branches a la recherche de gros fruits juteux. Il vit en communautes fission-fusion ou plusieurs femelles parentes partagent un territoire riche en arbres fruitiers, utilisant des nids foliacés pour elever les petits. Les adultes mesurent environ 50 a 60 cm de corps pour une queue touffue de 50 a 65 cm et pesent de 3 a 4,5 kg. Des donnees de captivite indiquent une esperance de vie pouvant atteindre ou depasser 30 ans, probablement plus faible en nature. Habitat typique: forets et aires protegees autour de Andasibe-Mantadia National Park.', 'Fortement frugivore (gros fruits juteux), mais consomme aussi nectar, fleurs et feuilles; role cle dans la dispersion des grosses graines.', 'EN DANGER CRITIQUE EXTINCTION', 1);-- Lemur-habitation links

INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (19, 1);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (5, 2);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (3, 3);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (17, 4);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (3, 5);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (3, 6);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (1, 7);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (5, 8);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (12, 9);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (5, 10);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (19, 11);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (11, 12);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (5, 13);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (1, 14);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (19, 15);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (19, 16);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (5, 17);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (2, 18);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (10, 19);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (6, 20);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (11, 21);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (21, 22);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (8, 23);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (11, 24);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (12, 25);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (19, 26);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (16, 27);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (5, 28);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (20, 29);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (2, 30);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (19, 31);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (13, 32);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (8, 33);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (17, 34);
INSERT INTO lemur_habitation (habitation_id, lemur_id) VALUES (2, 35);

COMMIT;
